### ISSUE TITLE
Adding an annotation when not logged in throws an error

### ISSUE THREAD

**Issue by huettenhain** [h2g2m/h2g2m#27]
This is because we attempt to retrieve the default tex header from the request.usr object, which does not exist.

**Comment by niknow** [comment]
I think this is one reason why we decided that one should not be able to add or modifiy annotations when not logged in, but maybe the interface should communicate this more clearly.

**Comment by huettenhain** [comment]
Sure, fine by me, let me just stress that this is not (only) an interface issue, there is an unhandled exception.

**Comment by niknow** [comment]
Agreed. Any action that requires a write access to the database should only be possible for a logged in user - otherwise the user should receive an error.
